name: Build Projects
on:
 - push

jobs:
  build:
    strategy:
      matrix:
        target:
          - StandaloneLinux64
          - StandaloneWindows64
          -  StandaloneWindows
          -  StandaloneOSX
          # - iOS
          - Android
          - WebGL
          # - WSAPlayer
    name: ${{ matrix.target }}
    runs-on: ubuntu-latest
    steps:
      - name: Clean the VM
        uses: jlumbroso/free-disk-space@main
        if: runner.os == 'ubuntu-latest'
        with:
          tool-cache: false
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          docker-images: true
          swap-storage: true

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true

      # Cache
      - name: Import from Cache
        uses: actions/cache@v3
        with:
          path: Library
          key: Library-${{ matrix.opt.target }}-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
          restore-keys: |
            Library-${{ matrix.opt.target }}-
            Library-
      # Build
      - name: Build project
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
         buildName: gwc
         targetPlatform: ${{ matrix.target }}
         allowDirtyBuild: true

      - uses: ${{ matrix.target == 'WebGL' && 'actions/upload-pages-artifact@v2' || 'actions/upload-artifact@v4' }}
        with:
          path: build/${{matrix.target}}${{ matrix.target == 'Android' && '/gwc.apk' || matrix.target == 'StandaloneOSX' && '/gwc.app' || matrix.target == 'WebGL' && '/gwc' }}
  gh-pages:
    name: GitHub Pages
    #if: github.ref == 'refs/heads/develop'
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{steps.deployment.outputs.page_url}}

    runs-on: ubuntu-latest
    steps:
      - id: deployment
        uses: actions/deploy-pages@v2
